board:
  init_nsvtor: 0x800c080

interrupt:
  mode: round-robin
  trigger:
    on-infinite-sleep: true
    interval: 1000

memory_maps:
  - name: mmio
    address: 0x40000000
    size: 0x20000000
    type: mmio
  - name: ITM_DWT_BPU
    address: 0xe0000000
    size: 0x3000
    type: mmio
  - name: CTI
    address: 0xe0042000
    size: 0x1000
    type: mmio
  - name: zero
    address: 0x0
    size: 0x1000
    type: ram
  - name: ram
    address: 0x20000000
    size: 0x30000
    type: ram
  - name: flash
    address: 0x8000000
    size: 0xc000
    type: ram
  - name: text
    address: 0x800c000
    size: 0xb400
    file:
      offset: 0x80
      path: uEmu.uTasker_MODBUS.bin
    type: rom

mmio_models:
  - context:
      mmio: 0x4002900c
    model:
      passthrough:
        initial_value: 0x0
  - context:
      mmio: 0x4002904c
    model:
      passthrough:
        initial_value: 0x0

symbols:
  - uEmu.uTasker_MODBUS.elf
