board:
  init_nsvtor: 0x80000

interrupt:
  mode: round-robin
  trigger:
    on-infinite-sleep: true
    interval: 1000

memory_maps:
  - name: mmio
    address: 0x40000000
    size: 0x20000000
    type: mmio
  - name: ITM_DWT_BPU
    address: 0xe0000000
    size: 0x3000
    type: mmio
  - name: CTI
    address: 0xe0042000
    size: 0x1000
    type: mmio
  - name: ram
    address: 0x20070000
    size: 0x40000
    type: ram
  - name: text
    address: 0x80000
    size: 0x7000
    file:
      path: Steering_Control.bin
    type: rom

symbols:
  - Steering_Control.elf
