handlers:
  fade: null
  lpm_enter: null
  printf: null
interrupt_triggers:
  idle_interrupt:
    addr: platform_idle
    irq: 0x9d
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x202000
    file: hello-world.bin
    ivt_offset: 0x0
    permissions: r-x
    size: 0x8e000
symbols:
  0x0: smartrf-sensors.c
  0x202000: vectors
  0x20228d: reset_handler
  0x2022cd: platform_init_stage_two
  0x202319: platform_init_stage_three
  0x2023a5: process_thread_sensors_process
  0x202481: value
  0x2024a5: configure
  0x2024f9: soc_get_rev
  0x202511: soc_print_info
  0x202521: update_ticks
  0x20256d: clock_init
  0x2025b9: clock_time
  0x2025cd: clock_seconds
  0x2025e1: clock_delay_usec
  0x2025fd: clock_adjust
  0x20261d: rtimer_arch_next_trigger
  0x202629: rtimer_arch_now
  0x202655: rtimer_arch_schedule
  0x2026ad: rtimer_isr
  0x2026d9: permit_pm1
  0x2026fd: uart_isr
  0x202761: uart_init
  0x202909: uart_set_input
  0x202919: uart_write_byte
  0x202935: watchdog_init
  0x202941: watchdog_start
  0x20294d: watchdog_periodic
  0x20295d: nvic_init
  0x20296d: sys_ctrl_init
  0x2029e1: gpio_port_isr
  0x202a2d: ioc_init
  0x202a49: ioc_set_over
  0x202a5d: ioc_set_sel
  0x202a71: adc_init
  0x202a81: adc_get
  0x202af9: permit_pm1
  0x202b09: crypto_isr
  0x202b31: crypto_enable
  0x202b51: crypto_init
  0x202b8d: crypto_disable
  0x202bad: gpio_hal_arch_no_port_pin_cfg_set
  0x202c8d: 'on'
  0x202cb5: 'off'
  0x202cf5: set_channel
  0x202d2d: channel_clear
  0x202d69: read
  0x202d91: receiving_packet
  0x202da9: pending_packet
  0x202db9: get_value
  0x202f1d: set_poll_mode
  0x202fb9: set_object
  0x202fe9: init
  0x2030d1: process_thread_cc2538_rf_process
  0x203161: get_object
  0x2032a5: transmit
  0x203349: prepare
  0x2033b1: set_value
  0x20353d: cc2538_rf_rx_tx_isr
  0x203561: cc2538_rf_err_isr
  0x203589: udma_init
  0x2035bd: udma_set_channel_src
  0x2035cd: udma_set_channel_dst
  0x2035e1: udma_set_channel_control_word
  0x2035f5: udma_channel_enable
  0x20360d: udma_channel_mask_set
  0x203625: udma_channel_sw_request
  0x20363d: udma_isr
  0x20364d: udma_err_isr
  0x203659: select_32_mhz_xosc
  0x203689: lpm_exit
  0x2036bd: lpm_enter
  0x203775: lpm_register_peripheral
  0x203799: lpm_init
  0x2037bd: pka_isr
  0x2037e5: ieee_addr_cpy_to
  0x203845: main
  0x203a31: stimer_expired
  0x203a51: update_time
  0x203a95: etimer_request_poll
  0x203aa1: process_thread_etimer_process
  0x203b4d: add_timer
  0x203b8d: etimer_pending
  0x203b9d: etimer_stop
  0x203bd1: log_6addr
  0x203bf1: log_lladdr
  0x203c2d: process_thread_ctimer_process
  0x203cad: ctimer_init
  0x203cd5: ctimer_set_with_process
  0x203d19: ctimer_set
  0x203d2d: ctimer_reset
  0x203d65: ctimer_stop
  0x203d91: ctimer_expired
  0x203dc5: rtimer_run_next
  0x203ded: node_id_init
  0x203e05: call_process.part.0
  0x203e3d: exit_process
  0x203ebd: do_poll
  0x203ef1: process_alloc_event
  0x203f01: process_exit
  0x203f0d: process_init
  0x203f3d: process_run
  0x203fc1: process_nevents
  0x203fd5: process_post
  0x204011: process_post_synch
  0x204025: process_start
  0x204055: process_poll
  0x20406d: stack_check_init
  0x204095: stack_check_get_usage
  0x2040d5: process_thread_stack_check_process
  0x204181: random_rand
  0x2041a1: random_init
  0x20421d: duration_exceeded_callback
  0x204251: process_thread_button_hal_process
  0x2042c1: press_release_handler
  0x2042d9: debounce_handler
  0x20433d: button_hal_init
  0x204431: process_thread_serial_line_process
  0x2044d1: serial_line_input_byte
  0x204515: serial_line_init
  0x204539: leds_on
  0x204599: leds_off
  0x2045e1: leds_init
  0x204625: gpio_hal_register_handler
  0x204631: gpio_hal_event_handler
  0x204655: gpio_hal_init
  0x204661: queuebuf_init
  0x20467d: queuebuf_numfree
  0x204689: queuebuf_new_from_packetbuf
  0x2046cd: queuebuf_free
  0x2046f9: queuebuf_to_packetbuf
  0x204729: index_from_key
  0x204749: index_from_lladdr
  0x204789: nbr_get_bit.constprop.0
  0x2047b5: nbr_table_is_registered
  0x2047d5: nbr_table_register
  0x204805: nbr_table_next
  0x20484d: nbr_table_head
  0x204885: nbr_table_add_lladdr
  0x2049f1: nbr_table_remove
  0x204a1d: nbr_table_lock
  0x204a2d: nbr_table_unlock
  0x204a3d: nbr_table_get_lladdr
  0x204a61: packetbuf_set_datalen
  0x204a6d: packetbuf_hdrptr
  0x204a75: packetbuf_datalen
  0x204a81: packetbuf_hdrlen
  0x204a99: packetbuf_dataptr
  0x204aa9: packetbuf_copyto
  0x204aed: packetbuf_totlen
  0x204b01: packetbuf_hdralloc
  0x204b41: packetbuf_attr_clear
  0x204b75: packetbuf_clear
  0x204b95: packetbuf_copyfrom
  0x204bc1: packetbuf_attr_copyto
  0x204be5: packetbuf_attr_copyfrom
  0x204c09: packetbuf_set_attr
  0x204c19: packetbuf_attr
  0x204c25: packetbuf_set_addr
  0x204c3d: packetbuf_addr
  0x204c4d: netstack_process_ip_callback
  0x204c8d: netstack_init
  0x204cb1: periodic
  0x204cdd: link_stats_from_lladdr
  0x204ce9: link_stats_packet_sent
  0x204d5d: link_stats_input_callback
  0x204dad: link_stats_reset
  0x204dd1: link_stats_init
  0x204df9: fill_space
  0x204e2d: format_str_v
  0x2054f5: printf
  0x205515: vsnprintf
  0x20553d: process_thread_ble_l2cap_tx_process
  0x2056a1: get_channel_for_addr
  0x2056e9: 'off'
  0x2056f9: 'on'
  0x20570d: send
  0x2057d9: init
  0x205939: input_l2cap_conn_req
  0x205a75: input
  0x205c71: uipbuf_add_ext_hdr
  0x205ca1: uipbuf_set_len
  0x205cb5: uipbuf_get_attr
  0x205cc9: uipbuf_clear_attr
  0x205cdd: uipbuf_clear
  0x205cfd: uipbuf_init
  0x205d1d: echo_reply_input
  0x205d89: echo_request_input
  0x205e21: uip_icmp6_input
  0x205e59: uip_icmp6_register_input_handler
  0x205e65: uip_icmp6_error_output
  0x205fa9: uip_icmp6_send
  0x206025: uip_icmp6_init
  0x206041: node_matches_address.part.0
  0x206069: uip_sr_get_node
  0x20609d: uip_sr_is_addr_reachable
  0x2060e1: uip_sr_update_node
  0x206185: uip_sr_init
  0x2061a9: uip_sr_periodic
  0x206211: uip_sr_free_all
  0x206251: uip_ds6_default_prefix
  0x206259: uip_ds6_prefix_add
  0x2062bd: uip_ds6_is_addr_onlink
  0x2062fd: uip_ds6_addr_lookup
  0x206329: uip_ds6_get_link_local
  0x206369: uip_ds6_maddr_add
  0x2063b5: uip_ds6_addr_add
  0x206449: uip_ds6_maddr_lookup
  0x206475: uip_ds6_addr_rm
  0x2064b9: uip_ds6_periodic
  0x206505: uip_ds6_select_src
  0x206599: uip_ds6_compute_reachable_time
  0x2065c5: uip_ds6_init
  0x2066dd: uip_ds6_route_init
  0x2066f9: uip_ds6_defrt_rm
  0x206731: uip_ds6_defrt_lookup
  0x206765: uip_ds6_defrt_add
  0x2067c5: uip_ds6_defrt_choose
  0x2067f5: uip_ds6_defrt_periodic
  0x206825: uip_ds6_nbr_rm
  0x206849: uip_ds6_neighbors_init
  0x206865: uip_ds6_nbr_add
  0x2068a5: uip_ds6_nbr_get_ll
  0x2068b1: uip_ds6_nbr_head
  0x2068bd: uip_ds6_nbr_next
  0x2068c9: uip_ds6_nbr_ll_lookup
  0x2068d5: tcpip_output
  0x206901: tcpip_input
  0x206925: tcpip_ipv6_output
  0x206a09: packet_input
  0x206a29: process_thread_tcpip_process
  0x206ae5: tcpip_uipcall
  0x206b11: upper_layer_chksum
  0x206b65: ext_hdr_options_process
  0x206be1: uip_update_ttl
  0x206c05: uip_init
  0x206c3d: uip_remove_ext_hdr
  0x206ca5: uip_process
  0x207101: ns_input
  0x207369: uip_nd6_init
  0x207375: clear_fragments
  0x2073b1: sicslowpan_init
  0x2073c9: set_packet_attrs
  0x207421: compress_addr_64
  0x2074b1: addr_context_lookup_by_prefix
  0x2074d5: send_packet
  0x2074f9: fragment_copy_payload_and_send
  0x207565: output
  0x207ce5: packet_sent
  0x207d41: store_fragment
  0x207d99: uncompress_addr
  0x207e29: add_fragment
  0x207f49: input
  0x2086e5: uiplib_ipaddr_snprint
  0x2087d5: update_state
  0x20884d: rpl_nbr_policy_find_removable
  0x20889d: remove_neighbor
  0x2088d9: rpl_neighbor_get_from_lladdr
  0x2088e9: rpl_neighbor_rank_via_nbr
  0x208901: rpl_neighbor_get_lladdr
  0x208911: best_parent
  0x2089a5: rpl_neighbor_is_parent
  0x2089bd: rpl_neighbor_set_preferred_parent
  0x208a05: rpl_neighbor_remove_all
  0x208a35: rpl_neighbor_get_from_ipaddr
  0x208a51: rpl_neighbor_select_best
  0x208aa5: rpl_neighbor_init
  0x208ab9: init_dag
  0x208b31: process_dio_init_dag
  0x208bd5: rpl_dag_get_root_ipaddr
  0x208c05: rpl_dag_leave
  0x208c59: rpl_dag_poison_and_leave
  0x208c69: rpl_dag_periodic
  0x208cb1: rpl_is_addr_in_our_dag
  0x208cd9: rpl_local_repair
  0x208d0d: rpl_global_repair
  0x208d45: rpl_dag_ready_to_advertise
  0x208d69: rpl_dag_update_state
  0x208e9d: rpl_process_dio
  0x209015: rpl_process_dis
  0x209041: rpl_process_dao
  0x20908d: rpl_process_dao_ack
  0x2090e1: rpl_dag_init_root
  0x209189: rpl_dag_init
  0x209199: new_dio_interval
  0x2091f1: schedule_dao_retransmission
  0x209221: handle_unicast_dio_timer
  0x20923d: send_new_dao
  0x209271: resend_dao
  0x2092a9: handle_dao_ack_timer
  0x2092bd: handle_leaving_timer
  0x2092cd: handle_dio_timer
  0x20933d: rpl_timers_schedule_periodic_dis
  0x209375: handle_dis_timer
  0x2093a9: handle_periodic_timer
  0x2093f1: rpl_timers_dio_reset
  0x209425: rpl_timers_schedule_unicast_dio
  0x20944d: rpl_timers_schedule_dao
  0x209481: rpl_timers_schedule_dao_ack
  0x2094c9: rpl_timers_notify_dao_ack
  0x209515: get_probing_target
  0x2095d5: rpl_schedule_probing
  0x2095fd: rpl_schedule_probing_now
  0x209629: rpl_timers_unschedule_leaving
  0x20964d: rpl_timers_schedule_leaving
  0x20967d: rpl_timers_init
  0x20969d: rpl_timers_stop_dag_timers
  0x2096e1: rpl_timers_unschedule_state_update
  0x2096f5: rpl_timers_schedule_state_update
  0x209711: update_hbh_header
  0x20975d: rpl_ext_header_srh_get_next_hop
  0x2097e1: rpl_ext_header_srh_update
  0x209885: rpl_ext_header_hbh_update
  0x209915: rpl_ext_header_remove
  0x2099c5: rpl_ext_header_update
  0x209c1d: rpl_has_joined
  0x209c35: rpl_is_reachable
  0x209c4d: rpl_get_leaf_only
  0x209c59: get_sr_node_ipaddr
  0x209c85: set_ip_from_prefix
  0x209cb1: init
  0x209cf1: rpl_link_callback
  0x209d1d: rpl_get_global_address
  0x209d81: rpl_reset_prefix
  0x209da9: rpl_set_prefix_from_addr
  0x209e19: update_metric_container
  0x209e25: within_hysteresis
  0x209e5d: rank_via_nbr
  0x209e8d: best_parent
  0x209efd: dao_ack_input
  0x209f35: dao_input
  0x20a035: dio_input
  0x20a249: dis_input
  0x20a275: rpl_icmp6_dis_output
  0x20a2ad: rpl_icmp6_dio_output
  0x20a46d: rpl_icmp6_dao_output
  0x20a531: rpl_icmp6_dao_ack_output
  0x20a575: rpl_icmp6_init
  0x20a5a5: rpl_dag_root_set_prefix
  0x20a60d: rpl_dag_root_start
  0x20a675: rpl_dag_root_is_root
  0x20a68d: process_thread_hello_world_process
  0x20a6d5: __aeabi_uldivmod
  0x20a705: __udivmoddi4
  0x20a9f1: __aeabi_idiv0
  0x20a9f5: memcmp
  0x20aa59: memcpy
  0x20ab45: memmove
  0x20ac0d: memset
  0x20aca9: strlen
  0x20ad05: default_handler
  0x20ad07: nmi_handler
  0x20ad0d: fade
  0x20ad65: platform_init_stage_one
  0x20ad79: platform_idle
  0x20ad7d: status
  0x20ad81: soc_init
  0x20ada3: clock_isr
  0x20ada7: rtimer_arch_init
  0x20ada9: uart0_isr
  0x20adaf: uart1_isr
  0x20adb5: gpio_port_a_isr
  0x20adbb: gpio_port_b_isr
  0x20adc1: gpio_port_c_isr
  0x20adc7: gpio_port_d_isr
  0x20adcd: send
  0x20addf: int_master_read_and_disable
  0x20ade7: int_master_status_set
  0x20aded: dbg_putchar
  0x20adfd: dbg_send_bytes
  0x20ae1d: configure
  0x20ae21: status
  0x20ae25: value
  0x20ae59: configure
  0x20ae5d: status
  0x20ae61: value
  0x20ae8b: autostart_start
  0x20ae9f: stimer_set
  0x20aead: energest_init
  0x20aeaf: etimer_set
  0x20aec1: etimer_reset
  0x20aed3: etimer_expired
  0x20aedd: rtimer_init
  0x20aee1: call_process
  0x20aeed: timer_set
  0x20aefb: timer_expired
  0x20af17: timer_reset
  0x20af2b: list_init
  0x20af31: list_head
  0x20af35: list_tail
  0x20af45: list_remove
  0x20af6b: list_add
  0x20af85: list_push
  0x20af95: list_item_next
  0x20af9b: memb_init
  0x20afbb: memb_alloc
  0x20afe3: memb_free
  0x20b00d: memb_inmemb
  0x20b029: memb_numfree
  0x20b045: ringbuf_init
  0x20b053: ringbuf_put
  0x20b079: ringbuf_get
  0x20b099: button_hal_get_state
  0x20b0c3: item_from_index
  0x20b0d7: index_from_item
  0x20b0ed: nbr_set_bit
  0x20b125: nbr_table_get_from_lladdr
  0x20b14b: linkaddr_copy
  0x20b151: linkaddr_cmp
  0x20b161: link_stats_is_fresh
  0x20b185: guess_etx_from_rssi
  0x20b1c5: mac_call_sent_callback
  0x20b1dd: write_str
  0x20b1ed: buffer_str
  0x20b215: snprintf
  0x20b22f: putchar
  0x20b23b: max_payload
  0x20b241: input_l2cap_connection_udate_resp
  0x20b265: input_l2cap_credit
  0x20b2af: uipbuf_set_len_field
  0x20b2b7: uipbuf_get_len_field
  0x20b2c3: uipbuf_get_next_header
  0x20b311: uipbuf_get_last_header
  0x20b33d: uipbuf_search_header
  0x20b37d: uip_sr_expire_parent
  0x20b3a5: uip_ds6_list_loop
  0x20b3f5: uip_ds6_maddr_rm
  0x20b3fd: uip_ds6_set_addr_iid
  0x20b413: uip_ds6_set_lladdr_from_iid
  0x20b429: get_match_length
  0x20b467: uip_ds6_route_nexthop
  0x20b46b: uip_ds6_route_lookup
  0x20b46f: uip_ds6_route_rm
  0x20b471: uip_ds6_nbr_lookup
  0x20b49d: uip_ds6_nbr_update_ll
  0x20b4fb: uip_ds6_nbr_ipaddr_from_lladdr
  0x20b4ff: uip_ds6_nbr_lladdr_from_ipaddr
  0x20b511: uip_ds6_link_callback
  0x20b513: chksum
  0x20b54b: uip_icmp6chksum
  0x20b551: uip_udpchksum
  0x20b557: uip_htonl
  0x20b569: rpl_neighbor_get_ipaddr
  0x20b577: rpl_neighbor_get_link_stats
  0x20b585: rpl_neighbor_is_fresh
  0x20b593: rpl_process_hbh
  0x20b5af: handle_state_update
  0x20b5b3: get_probing_delay
  0x20b5cd: handle_probing_timer
  0x20b5f1: drop_route
  0x20b5f3: neighbor_state_changed
  0x20b5f5: rpl_lollipop_greater_than
  0x20b629: reset
  0x20b62b: nbr_link_metric
  0x20b63d: nbr_has_usable_link
  0x20b64f: nbr_path_cost
  0x20b677: nbr_is_acceptable_parent
  0x20b695: get32
  0x20b6ad: set32
  0x20b6bf: get16
  0x20b6cb: set16
  0x20b6d5: rpl_icmp6_update_nbr_table
  0x20b704: als_sensor
  0x20b714: uart_regs
  0x20b76c: cc2538_rf_driver
  0x20b7a4: output_power
  0x20b814: cc2538_temp_sensor
  0x20b824: vdd3_sensor
  0x20b834: ble_l2cap_driver
  0x20b850: sicslowpan_driver
  0x20b860: rpl_lite_driver
  0x20b8b4: autostart_processes
  0x20b8bc: linkaddr_null
  0x20b8c4: leds_arch_leds
  0x20bb7c: buffer.5551
  0x20bb8c: buffer.5560
  0x20bc0f: unc_llconf
  0x20bc13: llprefix
  0x20bc15: unc_mxconf
  0x20bc24: ttl_values
  0x20bc28: unc_ctxconf
  0x20bd62: _etext
  0x20bd64: _ldata
  0x27ffd4: flash_cca_lock_page
  0x20000000: _enrdata
  0x20000040: _data
  0x20000050: sensors
  0x20000060: key_up
  0x200000b0: key_left
  0x20000100: key_select
  0x20000150: key_right
  0x200001a0: key_down
  0x200001f0: button_hal_buttons
  0x20000208: cc2538_rf_process
  0x20000218: etimer_process
  0x20000228: curr_log_level_main
  0x2000022c: ctimer_process
  0x2000023c: stack_check_process
  0x2000024c: button_hal_process
  0x2000025c: serial_line_process
  0x2000026c: bufmem
  0x20000278: buframmem
  0x20000284: neighbor_addr_mem
  0x20000290: link_stats_struct
  0x200002a0: ctxt
  0x200002a8: ble_l2cap_tx_process
  0x200002b8: echo_request_handler
  0x200002c4: echo_reply_handler
  0x200002d0: nodememb
  0x200002dc: defaultroutermemb
  0x200002e8: ds6_neighbors_struct
  0x200002f8: tcpip_process
  0x20000308: ns_input_handler
  0x20000314: rpl_neighbors
  0x20000318: rpl_neighbors_struct
  0x20000328: rpl_mrhof
  0x2000034c: dao_ack_handler
  0x20000358: dis_handler
  0x20000364: dao_handler
  0x20000370: dio_handler
  0x2000037c: hello_world_process
  0x2000038c: send_on_cca
  0x2000038d: rf_channel
  0x2000038e: _edata
  0x20000390: _bss
  0x20000398: rt_ticks_epoch
  0x200003a0: i.5534
  0x200003a4: events.5535
  0x200003a8: next_trigger
  0x200003ac: input_handler
  0x200003b4: ioc_sel
  0x200003b8: ioc_over
  0x200003bc: notification_process
  0x200003c0: prev_MDMTEST1
  0x200003c4: prev_FRMCTRL0
  0x200003c8: periph_permit_pm1_funcs
  0x200003dc: notification_process
  0x200003e0: timerlist
  0x200003e4: next_expiration
  0x200003e8: ctimer_list_list
  0x200003ec: next_rtimer
  0x200003f0: process_current
  0x200003f4: process_list
  0x200003f8: events
  0x20000578: et.5876
  0x20000588: button_event_handler
  0x20000594: pmask
  0x20000598: rxbuf
  0x200005a0: ptr.5519
  0x200005a4: handlers_list
  0x200005a8: bufmem_memb_mem
  0x200005c8: nbr_table_keys_list
  0x200005cc: neighbor_addr_mem_memb_mem
  0x2000068c: all_tables
  0x200006ac: num_tables
  0x200006b0: packetbuf_aligned
  0x20000730: ip_processor_list_list
  0x20000734: _link_stats_mem
  0x200007f4: echo_reply_callback_list_list
  0x200007f8: input_handler_list_list
  0x200007fc: num_nodes
  0x20000800: nodememb_memb_mem
  0x20000980: nodelist_list
  0x20000984: locmaddr
  0x20000988: locprefix
  0x2000098c: locaddr
  0x20000990: defaultroutermemb_memb_mem
  0x200009d0: defaultrouterlist_list
  0x200009d4: periodic
  0x200009e4: nbr
  0x200009e8: nd6_opt_llao
  0x200009ec: addr
  0x200009f0: callback
  0x200009f4: context
  0x200009f8: last_rssi
  0x200009fc: hc06_ptr
  0x20000a00: packetbuf_ptr
  0x20000a04: packetbuf_payload_len
  0x20000a08: last_tx_status
  0x20000a0c: mac_max_payload
  0x20000a10: frag_info
  0x20000b80: worst_rank_nbr_lladdr
  0x20000b84: num_parents
  0x20000b88: _rpl_neighbors_mem
  0x20000c08: periodic_timer
  0x20000c28: dis_timer
  0x20000c48: timer.5488
  0x20000c58: node_id
  0x20000c5a: buframmem_memb_mem
  0x200011ba: buflen
  0x200011bc: bufptr
  0x200011be: l2cap_channels
  0x20001bde: uipbuf_attrs
  0x20001bea: uipbuf_default_attrs
  0x20001bf6: tmp_ipaddr
  0x20001c06: default_prefix
  0x20001c16: loc_fipaddr
  0x20001c26: _ds6_neighbors_mem
  0x20001d46: uip_ext_len
  0x20001d48: lastport
  0x20001d4a: my_tag
  0x20001d4c: worst_rank
  0x20001d4e: root_ipaddr.7069
  0x20001d5e: num_sensors
  0x20001d5f: was_on
  0x20001d60: poll_mode
  0x20001d61: rf_flags
  0x20001d62: max_pm
  0x20001d63: initialized
  0x20001d64: fevent
  0x20001d65: nevents
  0x20001d66: poll_requested
  0x20001d67: lastevent
  0x20001d68: rxbuf_data
  0x20001de8: overflow.5512
  0x20001de9: buf.5518
  0x20001e69: buframmem_memb_used
  0x20001e71: bufmem_memb_used
  0x20001e79: locked_map
  0x20001e89: neighbor_addr_mem_memb_used
  0x20001e99: used_map
  0x20001ea9: hdrlen
  0x20001eaa: l2cap_channel_count
  0x20001eab: l2cap_tx_event
  0x20001eac: ble_addr
  0x20001eb2: nodememb_memb_used
  0x20001ec2: defaultroutermemb_memb_used
  0x20001ec4: uip_ext_bitmap
  0x20001ec5: uip_last_proto
  0x20001ec6: nd6_opt_offset
  0x20001ec7: curr_page
  0x20001ec8: uncomp_hdr_len
  0x20001ec9: addr_contexts
  0x20001ed3: frag_buf
  0x2000241f: packetbuf_hdr_len
  0x20002420: rpl_leaf_only
  0x20002421: initialized.7080
  0x20002424: periodic_timer
  0x20002444: uip_ds6_timer_ra
  0x2000244c: uip_ds6_if
  0x20002544: uip_ds6_netif_addr_list_offset
  0x20002545: uip_ds6_addr_size
  0x20002548: uip_ds6_prefix_list
  0x200025a8: uip_ds6_timer_periodic
  0x200025b8: uip_len
  0x200025bc: uip_sappdata
  0x200025c0: uip_lladdr
  0x200025c8: uip_aligned_buf
  0x20002ac8: uip_flags
  0x20002acc: uip_udp_conn
  0x20002ad0: uip_appdata
  0x20002ad4: uip_conn
  0x20002ad8: uip_slen
  0x20002adc: uip_udp_conns
  0x20002bdc: curr_instance
  0x20002d3c: packetbuf_addrs
  0x20002d4c: packetbuf_attrs
  0x20002d66: linkaddr_node_addr
  0x20002d6e: rpl_multicast_addr
  0x20002d7e: sensors_event
  0x20002d7f: sensors_flags
  0x20002d83: button_hal_release_event
  0x20002d84: button_hal_periodic_event
  0x20002d85: button_hal_press_event
  0x20002d86: serial_line_event_message
  0x20002d87: tcpip_event
  0x20002d88: _stack
  0x20003588: _heap
  0x20008000: _eheap
