board:
  init_nsvtor: 0x8000000

interrupt:
  mode: round-robin
  trigger:
    on-infinite-sleep: true
    interval: 1000

memory_maps:
  - name: mmio
    address: 0x40000000
    size: 0x20000000
    type: mmio
  - name: ITM_DWT_BPU
    address: 0xe0000000
    size: 0x3000
    type: mmio
  - name: CTI
    address: 0xe0042000
    size: 0x1000
    type: mmio
  - name: ram
    address: 0x20000000
    size: 0x100000
    type: ram
  - name: text
    address: 0x8000000
    size: 0x6000
    file:
      path: uEmu.LiteOS_IoT.bin
      length: 0x6000
    type: rom
  - name: rodata
    address: 0x8006000
    size: 0x4000
    permission:
      executable: false
    file:
      path: uEmu.LiteOS_IoT.bin
      seek: 0x6000
    type: rom

symbols:
  - uEmu.LiteOS_IoT.elf
