board:
  init_nsvtor: 0x80000

interrupt:
  mode: round-robin
  trigger:
    on-infinite-sleep: true
    interval: 1000

memory_maps:
  - name: mmio
    address: 0x40000000
    size: 0x20000000
    type: mmio
  - name: ITM_DWT_BPU
    address: 0xe0000000
    size: 0x3000
    type: mmio
  - name: CTI
    address: 0xe0042000
    size: 0x1000
    type: mmio
  - name: mmio_UDD
    address: 0x20180000
    size: 0x20000
    type: mmio
  - name: flash
    address: 0xa0000
    size: 0x1000
    type: ram
  - name: ram
    address: 0x20070000
    size: 0x90000
    type: ram
  - name: text
    address: 0x80000
    size: 0xc000
    file:
      path: uEmu.GPSTracker.bin
    type: rom

symbols:
  - uEmu.GPSTracker.elf
