board:
  init_nsvtor: 0x8000000

interrupt:
  mode: fuzzed
  trigger:
    on-infinite-sleep: false
    interval: false
    custom:
      - name: idle_interrupt
        symbol: arch_cpu_idle

memory_maps:
  - name: mmio
    address: 0x40000000
    size: 0x20000000
    type: mmio
  - name: ITM_DWT_BPU
    address: 0xe0000000
    size: 0x3000
    type: mmio
  - name: CTI
    address: 0xe0042000
    size: 0x1000
    type: mmio
  - name: ram
    address: 0x20000000
    size: 0x100000
    type: ram
  - name: text
    address: 0x8000000
    size: 0x1d000
    file:
      path: zephyr-CVE-2020-10066.bin
    type: rom

exit_hooks:
  - name: arch_system_halt
    symbol: arch_system_halt
  - name: z_do_kernel_oops
    symbol: z_do_kernel_oops
  - name: z_fatal_error
    symbol: z_fatal_error

symbols:
  - zephyr-CVE-2020-10066.elf
script: |
  pub fn main(api) {
    api.on_init(on_init);
  }
  
  fn on_init() {
    common::patch_function("arch_system_halt", arm::RETURN);
    common::patch_function("printk", arm::RETURN);
    common::patch_function("z_impl_k_busy_wait", arm::RETURN);
    common::patch_function("z_impl_k_sleep", arm::RETURN);
    common::patch_function("z_vprintk", arm::RETURN);
  }
