interrupt:
  mode: round-robin
  trigger:
    on-infinite-sleep: true
    interval: 1000

memory_maps:
  - name: mmio
    address: 0x40000000
    size: 0x20000000
    type: mmio
  - name: ITM_DWT_BPU
    address: 0xe0000000
    size: 0x3000
    type: mmio
  - name: CTI
    address: 0xe0042000
    size: 0x1000
    type: mmio
  - name: ram
    address: 0x1fff0000
    size: 0x10000
    type: ram
  - name: text
    address: 0x0
    size: 0x8000
    file:
      path: Console.bin
    type: rom

symbols:
  - Console.elf
