interrupt:
  mode: round-robin
  trigger:
    interval: 0x3e8
    on-infinite-sleep: true

board:
  init_nsvtor: 0x200000

memory_maps:
  - name: mmio
    address: 0x40000000
    size: 0x20000000
    type: mmio
  - name: ram
    address: 0x20000000
    size: 0x100000
    type: ram
  - name: text
    address: 0x200000
    size: 0x80000
    file:
      path: gnrc_networking.bin
    type: rom
  - name: cpuid
    address: 0x280000
    size: 0x400
    type: rom

symbols:
  - gnrc_networking.elf

exit_hooks:
  - symbol: _assert_panic
  - symbol: RFCORE_ASSERT_failure
