board:
  init_nsvtor: 0x400000

interrupt:
  mode: fuzzed
  trigger:
    on-infinite-sleep: false
    interval: false
    custom:
      - name: idle_interrupt
        symbol: arch_cpu_idle

memory_maps:
  - name: bss
    address: 0x20102000
    size: 0x2000
    type: ram
  - name: mmio
    address: 0x40000000
    size: 0x20000000
    type: mmio
  - name: noinit
    address: 0x20104000
    size: 0x8400
    type: ram
  - name: ITM_DWT_BPU
    address: 0xe0000000
    size: 0x3000
    type: mmio
  - name: CTI
    address: 0xe0042000
    size: 0x1000
    type: mmio
  - name: ram
    address: 0x20000000
    size: 0x102000
    type: ram
  - name: text
    address: 0x400000
    size: 0x24000
    file:
      path: zephyr-CVE-2021-3323.bin
    type: rom

exit_hooks:
  - name: arch_system_halt
    symbol: arch_system_halt
  - name: quit
    symbol: quit
  - name: z_do_kernel_oops
    symbol: z_do_kernel_oops
  - name: z_fatal_error
    symbol: z_fatal_error

symbols:
  - zephyr-CVE-2021-3323.elf
script: |
  pub fn main(api) {
    api.on_init(on_init);
  }
  
  fn on_init() {
    common::patch_function("arch_system_halt", arm::RETURN);
    common::patch_function("log_0", arm::RETURN);
    common::patch_function("log_1", arm::RETURN);
    common::patch_function("log_2", arm::RETURN);
    common::patch_function("log_3", arm::RETURN);
    common::patch_function("log_n", arm::RETURN);
    common::patch_function("printk", arm::RETURN);
    common::patch_function("z_impl_k_busy_wait", arm::RETURN);
    common::patch_function("z_impl_k_sleep", arm::RETURN);
  }
