board:
  init_nsvtor: 0x08000000

interrupt:
  mode: fuzzed
  trigger:
    on-infinite-sleep: true
    interval: 0

memory_maps:
  - name: text
    address: 0x08000000
    size: 0x10800
    file:
      path: zephyr.bin
    type: rom
  - name: ram
    address: 0x20000000
    size: 0x10000
    type: ram
  - name: mmio
    address: 0x40000000
    size: 0x20000000
    type: mmio

symbols:
  - zephyr.elf

exit_hooks:
  - symbol: arch_system_halt
  - symbol: z_do_kernel_oops
  - symbol: z_fatal_error

debug_hooks:
  - symbol: printk
    type: printf

script: |
  pub fn main(api) {
    api.on_init(on_init);
  }

  fn on_init() {
    common::patch_function("z_arm_mpu_init", arm::RETURN)?;
    common::patch_function("arm_core_mpu_configure_dynamic_mpu_regions", arm::RETURN)?;
    common::patch_function("arm_core_mpu_configure_static_mpu_regions", arm::RETURN)?;

    common::patch_function("z_impl_k_busy_wait", arm::RETURN)?;
    common::patch_function("z_impl_k_sleep", arm::RETURN)?;

    common::patch_function("printk", arm::RETURN)?;
  }
