board:
  init_nsvtor: 0x202000

interrupt:
  mode: round-robin
  trigger:
    on-infinite-sleep: true
    interval: 0x0
  allowlist:
    - 0x9d

memory_maps:
  - name: mmio
    address: 0x40000000
    size: 0x20000000
    type: mmio
  - name: ram
    address: 0x20000000
    size: 0x100000
    type: ram
  - name: text
    address: 0x202000
    size: 0x8e000
    file:
      path: ip64-router.bin
    type: rom

symbols:
  - ip64-router.elf

script: |-
  pub fn main(api) {
    api.on_init(on_init);
  }

  fn on_init() {
    common::patch_function("platform_idle", arm::WFI_RETURN);
    common::patch_function("printf", arm::RETURN);
    common::patch_function("fade", arm::RETURN);
    common::patch_function("lpm_enter", arm::RETURN);
  }
