board:
  init_nsvtor: 0x8000000

interrupt:
  mode: round-robin
  trigger:
    on-infinite-sleep: true
    interval: 1000

memory_maps:
  - name: mmio
    address: 0x40000000
    size: 0x20000000
    type: mmio
  - name: ITM_DWT_BPU
    address: 0xe0000000
    size: 0x3000
    type: mmio
  - name: CTI
    address: 0xe0042000
    size: 0x1000
    type: mmio
  - name: zero
    address: 0x0
    size: 0x1000
    type: ram
  - name: ram
    address: 0x20000000
    size: 0x40000
    type: ram
  - name: text
    address: 0x8000000
    size: 0xb000
    file:
      path: Robot.bin
    type: rom

symbols:
  - Robot.elf
