handlers:
  fade: null
  lpm_enter: null
  printf: null
interrupt_triggers:
  idle_interrupt:
    addr: platform_idle
    irq: 0x9d
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x202000
    file: snmp-server.bin
    ivt_offset: 0x0
    permissions: r-x
    size: 0x8e000
symbols:
  0x0: smartrf-sensors.c
  0x202000: vectors
  0x20228d: reset_handler
  0x2022cd: platform_init_stage_two
  0x202319: platform_init_stage_three
  0x2023a5: process_thread_sensors_process
  0x202481: value
  0x2024a5: configure
  0x2024f9: soc_get_rev
  0x202511: soc_print_info
  0x202521: update_ticks
  0x20256d: clock_init
  0x2025b9: clock_time
  0x2025cd: clock_seconds
  0x2025e1: clock_delay_usec
  0x2025fd: clock_adjust
  0x20261d: rtimer_arch_next_trigger
  0x202629: rtimer_arch_now
  0x202655: rtimer_arch_schedule
  0x2026ad: rtimer_isr
  0x2026d9: permit_pm1
  0x2026fd: uart_isr
  0x202761: uart_init
  0x202909: uart_set_input
  0x202919: uart_write_byte
  0x202935: watchdog_init
  0x202941: watchdog_start
  0x20294d: watchdog_periodic
  0x20295d: nvic_init
  0x20296d: sys_ctrl_init
  0x2029e1: gpio_port_isr
  0x202a2d: ioc_init
  0x202a49: ioc_set_over
  0x202a5d: ioc_set_sel
  0x202a71: adc_init
  0x202a81: adc_get
  0x202af9: permit_pm1
  0x202b09: crypto_isr
  0x202b31: crypto_enable
  0x202b51: crypto_init
  0x202b8d: crypto_disable
  0x202bad: gpio_hal_arch_no_port_pin_cfg_set
  0x202c8d: 'on'
  0x202cb5: 'off'
  0x202cf5: set_channel
  0x202d2d: channel_clear
  0x202d69: read
  0x202d91: receiving_packet
  0x202da9: pending_packet
  0x202db9: get_value
  0x202f1d: set_poll_mode
  0x202fb9: set_object
  0x202fe9: init
  0x2030c9: process_thread_cc2538_rf_process
  0x20315d: get_object
  0x2032a1: transmit
  0x203349: prepare
  0x2033b5: set_value
  0x203541: cc2538_rf_rx_tx_isr
  0x203565: cc2538_rf_err_isr
  0x20358d: udma_init
  0x2035c1: udma_set_channel_src
  0x2035d1: udma_set_channel_dst
  0x2035e5: udma_set_channel_control_word
  0x2035f9: udma_channel_enable
  0x203611: udma_channel_mask_set
  0x203629: udma_channel_sw_request
  0x203641: udma_isr
  0x203651: udma_err_isr
  0x20365d: select_32_mhz_xosc
  0x20368d: lpm_exit
  0x2036c1: lpm_enter
  0x203779: lpm_register_peripheral
  0x20379d: lpm_init
  0x2037c1: pka_isr
  0x2037e9: ieee_addr_cpy_to
  0x203849: sysDescr_handler
  0x203855: sysContact_handler
  0x203861: sysName_handler
  0x20386d: sysLocation_handler
  0x203879: sysObjectID_handler
  0x203885: uipbuf_add_ext_hdr
  0x2038b5: uipbuf_set_len
  0x2038c9: uipbuf_clear_attr
  0x2038dd: uipbuf_clear
  0x2038fd: uipbuf_init
  0x20391d: echo_reply_input
  0x203989: echo_request_input
  0x203a21: uip_icmp6_input
  0x203a59: uip_icmp6_register_input_handler
  0x203a65: uip_icmp6_error_output
  0x203ba9: uip_icmp6_init
  0x203bc5: uip_ds6_prefix_add
  0x203c29: uip_ds6_is_addr_onlink
  0x203c69: uip_ds6_addr_lookup
  0x203c95: uip_ds6_get_link_local
  0x203cd5: uip_ds6_maddr_add
  0x203d21: uip_ds6_addr_add
  0x203db5: uip_ds6_maddr_lookup
  0x203de1: uip_ds6_addr_rm
  0x203e25: uip_ds6_select_src
  0x203eb9: uip_ds6_send_ra_sollicited
  0x203eed: uip_ds6_send_ra_periodic
  0x203f3d: uip_ds6_periodic
  0x203fa9: uip_ds6_compute_reachable_time
  0x203fd5: uip_ds6_init
  0x2040f9: uip_udp_packet_send
  0x20412d: call_route_callback
  0x20417d: uip_ds6_route_init
  0x2041c9: uip_ds6_route_nexthop
  0x2041e5: uip_ds6_route_head
  0x2041f1: uip_ds6_route_lookup
  0x204259: uip_ds6_route_rm
  0x2042ed: rm_routelist
  0x20431d: uip_ds6_defrt_rm
  0x204361: uip_ds6_defrt_lookup
  0x204395: uip_ds6_defrt_choose
  0x2043c5: uip_ds6_defrt_periodic
  0x2043f5: uip_ds6_nbr_rm
  0x204419: uip_ds6_neighbors_init
  0x204435: uip_ds6_nbr_add
  0x20449d: uip_ds6_nbr_get_ll
  0x2044a9: uip_ds6_nbr_head
  0x2044b5: uip_ds6_nbr_next
  0x2044c1: uip_ds6_nbr_ll_lookup
  0x2044cd: uip_ds6_neighbor_periodic
  0x2045cd: tcpip_output
  0x2045f9: udp_new
  0x204611: tcpip_ipv6_output
  0x204749: packet_input
  0x204769: process_thread_tcpip_process
  0x204825: tcpip_uipcall
  0x204851: upper_layer_chksum
  0x2048a5: ext_hdr_options_process
  0x204921: uip_update_ttl
  0x204945: uip_init
  0x20497d: uip_remove_ext_hdr
  0x2049e5: uip_udp_new
  0x204a71: uip_process
  0x204edd: extract_lladdr_from_llao_aligned
  0x204efd: create_llao
  0x204f25: rs_input
  0x205091: na_input
  0x205221: ns_input
  0x205469: uip_nd6_ns_output
  0x2055b5: uip_nd6_ra_output
  0x20579d: uip_nd6_init
  0x2057c1: uiplib_ipaddr_snprint
  0x2058b1: snmp_message_decode
  0x205bb9: snmp_mib_find
  0x205bdd: snmp_mib_find_next
  0x205c05: snmp_mib_add
  0x205c41: snmp_mib_init
  0x205c4d: process_thread_snmp_process
  0x205db1: snmp_init
  0x205dc9: snmp_engine
  0x205ea1: main
  0x206091: stimer_expired
  0x2060b1: update_time
  0x2060f5: etimer_request_poll
  0x206101: process_thread_etimer_process
  0x2061ad: add_timer
  0x2061ed: etimer_pending
  0x2061fd: etimer_stop
  0x206231: log_6addr
  0x206251: log_lladdr
  0x20628d: process_thread_ctimer_process
  0x20630d: ctimer_init
  0x206335: ctimer_set_with_process
  0x206379: ctimer_set
  0x20638d: ctimer_reset
  0x2063c5: ctimer_stop
  0x2063f1: ctimer_expired
  0x206425: rtimer_run_next
  0x20644d: node_id_init
  0x206465: call_process.part.0
  0x20649d: exit_process
  0x20651d: do_poll
  0x206551: process_alloc_event
  0x206561: process_init
  0x206591: process_run
  0x206615: process_nevents
  0x206629: process_post
  0x206665: process_post_synch
  0x206679: process_start
  0x2066a9: process_poll
  0x2066c1: stack_check_init
  0x2066e9: stack_check_get_usage
  0x206729: process_thread_stack_check_process
  0x2067d5: random_rand
  0x2067f5: random_init
  0x206871: duration_exceeded_callback
  0x2068a5: process_thread_button_hal_process
  0x206915: press_release_handler
  0x20692d: debounce_handler
  0x206991: button_hal_init
  0x206a85: process_thread_serial_line_process
  0x206b25: serial_line_input_byte
  0x206b69: serial_line_init
  0x206b8d: leds_on
  0x206bed: leds_off
  0x206c35: leds_init
  0x206c79: gpio_hal_register_handler
  0x206c85: gpio_hal_event_handler
  0x206ca9: gpio_hal_init
  0x206cb5: queuebuf_init
  0x206cd1: index_from_key
  0x206cf1: index_from_lladdr
  0x206d31: nbr_get_bit.constprop.1
  0x206d5d: nbr_table_is_registered
  0x206d7d: nbr_table_register
  0x206dad: nbr_table_next
  0x206df5: nbr_table_head
  0x206e2d: nbr_table_add_lladdr
  0x206f55: nbr_table_remove
  0x206f81: nbr_table_get_lladdr
  0x206fa5: packetbuf_set_datalen
  0x206fb1: packetbuf_datalen
  0x206fbd: packetbuf_hdrlen
  0x206fd5: packetbuf_dataptr
  0x206fe5: packetbuf_attr_clear
  0x207019: packetbuf_clear
  0x207039: packetbuf_copyfrom
  0x207069: packetbuf_set_addr
  0x207081: packetbuf_addr
  0x207091: netstack_process_ip_callback
  0x2070d1: netstack_init
  0x2070f5: periodic
  0x207121: link_stats_init
  0x207149: fill_space
  0x20717d: format_str_v
  0x207845: printf
  0x207865: vsnprintf
  0x20788d: packet_input
  0x207899: 'on'
  0x2078a5: 'off'
  0x2078b1: max_payload
  0x2078c9: send_packet
  0x2078e5: init
  0x2078f1: output
  0x20793d: input
  0x207979: nullnet_set_input_callback
  0x207985: nullnet_input_callback_snmp
  0x207999: process_thread_snmp_server_process
  0x2079f9: __aeabi_uldivmod
  0x207a29: __udivmoddi4
  0x207d15: __aeabi_idiv0
  0x207d19: div
  0x207d51: memcmp
  0x207db5: memcpy
  0x207ea1: memmove
  0x207f69: memset
  0x208005: strlen
  0x208061: strncmp
  0x2080fd: default_handler
  0x2080ff: nmi_handler
  0x208105: fade
  0x20815d: platform_init_stage_one
  0x208171: platform_idle
  0x208175: status
  0x208179: soc_init
  0x20819b: clock_isr
  0x20819f: rtimer_arch_init
  0x2081a1: uart0_isr
  0x2081a7: uart1_isr
  0x2081ad: gpio_port_a_isr
  0x2081b3: gpio_port_b_isr
  0x2081b9: gpio_port_c_isr
  0x2081bf: gpio_port_d_isr
  0x2081c5: send
  0x2081d7: int_master_read_and_disable
  0x2081df: int_master_status_set
  0x2081e5: dbg_putchar
  0x2081f5: dbg_send_bytes
  0x208215: configure
  0x208219: status
  0x20821d: value
  0x208251: configure
  0x208255: status
  0x208259: value
  0x208283: sysServices_handler
  0x20829d: sysUpTime_handler
  0x2082a1: uipbuf_set_len_field
  0x2082a9: uipbuf_get_len_field
  0x2082b5: uipbuf_get_next_header
  0x208303: uipbuf_get_last_header
  0x20832f: uip_ds6_list_loop
  0x20837f: uip_ds6_maddr_rm
  0x208387: uip_ds6_set_addr_iid
  0x20839d: get_match_length
  0x2083db: uip_udp_packet_sendto
  0x20842b: uip_ds6_route_next
  0x208433: rm_routelist_callback
  0x208437: uip_ds6_nbr_lookup
  0x208463: uip_ds6_nbr_update_ll
  0x2084c1: uip_ds6_nbr_ipaddr_from_lladdr
  0x2084c5: uip_ds6_nbr_refresh_reachable_state
  0x2084e5: chksum
  0x20851d: uip_icmp6chksum
  0x208523: uip_udpchksum
  0x208529: uip_htons
  0x20852f: uip_htonl
  0x208541: snmp_message_encode
  0x208657: snmp_oid_cmp_oid
  0x208691: snmp_oid_encode_oid
  0x208719: snmp_oid_decode_oid
  0x2087cb: snmp_oid_copy
  0x2087eb: snmp_ber_encode_type
  0x2087f7: snmp_ber_encode_length
  0x208803: snmp_ber_encode_integer
  0x208835: snmp_ber_encode_unsigned_integer
  0x208865: snmp_ber_encode_string_len
  0x20889f: snmp_ber_encode_null
  0x2088b5: snmp_ber_decode_type
  0x2088c3: snmp_ber_decode_length
  0x2088d1: snmp_ber_decode_integer
  0x20891d: snmp_ber_decode_unsigned_integer
  0x208969: snmp_ber_decode_string_len_buffer
  0x2089d7: snmp_ber_decode_null
  0x2089e1: snmp_engine_get
  0x208a2f: snmp_engine_get_next
  0x208a7d: snmp_engine_get_bulk
  0x208bc5: snmp_api_replace_oid
  0x208bdb: snmp_api_set_string
  0x208bf7: snmp_api_set_time_ticks
  0x208c09: snmp_api_set_oid
  0x208c1b: snmp_api_add_resource
  0x208c1f: autostart_start
  0x208c33: stimer_set
  0x208c41: stimer_remaining
  0x208c51: stimer_elapsed
  0x208c5f: energest_init
  0x208c61: etimer_set
  0x208c73: etimer_reset
  0x208c85: etimer_expired
  0x208c8f: rtimer_init
  0x208c93: call_process
  0x208c9f: timer_set
  0x208cad: timer_expired
  0x208cc9: timer_reset
  0x208cdd: list_init
  0x208ce3: list_head
  0x208ce7: list_tail
  0x208cf7: list_remove
  0x208d1d: list_add
  0x208d37: list_push
  0x208d47: list_length
  0x208d55: list_insert
  0x208d73: list_item_next
  0x208d79: memb_init
  0x208d99: memb_alloc
  0x208dc1: memb_free
  0x208deb: ringbuf_init
  0x208df9: ringbuf_put
  0x208e1f: ringbuf_get
  0x208e3f: button_hal_get_state
  0x208e69: item_from_index
  0x208e7d: index_from_item
  0x208e93: nbr_set_bit
  0x208ecb: nbr_table_get_from_lladdr
  0x208ef1: linkaddr_copy
  0x208ef7: linkaddr_cmp
  0x208f07: write_str
  0x208f17: buffer_str
  0x208f3f: snprintf
  0x208f59: putchar
  0x208f65: init
  0x208f69: root_set_prefix
  0x208f6b: get_sr_node_ipaddr
  0x208f6f: leave_network
  0x208f71: ext_header_update
  0x208f75: ext_header_hbh_update
  0x208f79: ext_header_srh_update
  0x208f7d: ext_header_srh_get_next_hop
  0x208f81: link_callback
  0x208f83: drop_route
  0x208f85: is_in_leaf_mode
  0x208f89: ext_header_remove
  0x208f8d: get_root_ipaddr
  0x208f91: node_has_joined
  0x208f95: node_is_reachable
  0x208f99: global_repair
  0x208f9b: local_repair
  0x208f9d: neighbor_state_changed
  0x208f9f: root_start
  0x208fa3: node_is_root
  0x208fa7: init
  0x208fa8: als_sensor
  0x208fb8: uart_regs
  0x209010: cc2538_rf_driver
  0x209048: output_power
  0x2090b8: cc2538_temp_sensor
  0x2090c8: vdd3_sensor
  0x2090d8: nullmac_driver
  0x2090f4: nullnet_driver
  0x209104: nullrouting_driver
  0x209158: autostart_processes
  0x209160: linkaddr_null
  0x209168: leds_arch_leds
  0x2096e7: buffer.5551
  0x2096f7: buffer.5560
  0x20975c: _ldata
  0x27ffd4: flash_cca_lock_page
  0x20000000: _enrdata
  0x20000040: _data
  0x20000050: sensors
  0x20000060: key_up
  0x200000b0: key_left
  0x20000100: key_select
  0x20000150: key_right
  0x200001a0: key_down
  0x200001f0: button_hal_buttons
  0x20000208: cc2538_rf_process
  0x20000218: sysObjectID
  0x20000224: sysLocation
  0x20000230: sysLocation_oid
  0x20000258: sysName
  0x20000264: sysContact_oid
  0x2000028c: sysDescr_oid
  0x200002b4: sysServices_oid
  0x200002dc: sysContact
  0x200002e8: sysDescr
  0x200002f4: sysUpTime_oid
  0x2000031c: sysServices
  0x20000328: sysObjectID_oid
  0x20000350: sysObjectID_oid.7084
  0x20000370: sysUpTime
  0x2000037c: sysName_oid
  0x200003a4: echo_request_handler
  0x200003b0: echo_reply_handler
  0x200003bc: defaultroutermemb
  0x200003c8: nbr_routes_struct
  0x200003d8: nbr_routes
  0x200003dc: routememb
  0x200003e8: neighborroutememb
  0x200003f4: ds6_neighbors_struct
  0x20000404: tcpip_process
  0x20000414: rs_input_handler
  0x20000420: ns_input_handler
  0x2000042c: na_input_handler
  0x20000438: snmp_process
  0x20000448: etimer_process
  0x20000458: curr_log_level_main
  0x2000045c: curr_log_level_snmp
  0x20000460: ctimer_process
  0x20000470: stack_check_process
  0x20000480: button_hal_process
  0x20000490: serial_line_process
  0x200004a0: bufmem
  0x200004ac: buframmem
  0x200004b8: neighbor_addr_mem
  0x200004c4: link_stats_struct
  0x200004d4: ctxt
  0x200004dc: snmp_server_process
  0x200004ec: send_on_cca
  0x200004ed: rf_channel
  0x200004ee: _edata
  0x200004f0: _bss
  0x200004f8: rt_ticks_epoch
  0x20000500: i.5534
  0x20000504: events.5535
  0x20000508: next_trigger
  0x2000050c: input_handler
  0x20000514: ioc_sel
  0x20000518: ioc_over
  0x2000051c: notification_process
  0x20000520: prev_MDMTEST1
  0x20000524: prev_FRMCTRL0
  0x20000528: periph_permit_pm1_funcs
  0x2000053c: notification_process
  0x20000540: echo_reply_callback_list_list
  0x20000544: input_handler_list_list
  0x20000548: locmaddr
  0x2000054c: locprefix
  0x20000550: locaddr
  0x20000554: defaultroutermemb_memb_mem
  0x20000594: num_routes
  0x20000598: defaultrouterlist_list
  0x2000059c: _nbr_routes_mem
  0x2000061c: routelist_list
  0x20000620: routememb_memb_mem
  0x200008a0: neighborroutememb_memb_mem
  0x20000920: notificationlist_list
  0x20000924: _ds6_neighbors_mem
  0x20000ba4: periodic
  0x20000bb4: prefix
  0x20000bb8: nbr
  0x20000bbc: nd6_opt_llao
  0x20000bc0: addr
  0x20000bc4: snmp_mib_list
  0x20000bc8: snmp_udp_conn
  0x20000bcc: packet_len.7064
  0x20000bd0: varbind_length.7147
  0x20000bd4: varbinds.7146
  0x20000c6c: header.7145
  0x20000c88: timerlist
  0x20000c8c: next_expiration
  0x20000c90: ctimer_list_list
  0x20000c94: next_rtimer
  0x20000c98: process_current
  0x20000c9c: process_list
  0x20000ca0: events
  0x20000e20: et.5876
  0x20000e30: button_event_handler
  0x20000e3c: pmask
  0x20000e40: rxbuf
  0x20000e48: ptr.5519
  0x20000e4c: handlers_list
  0x20000e50: bufmem_memb_mem
  0x20000e70: nbr_table_keys_list
  0x20000e74: neighbor_addr_mem_memb_mem
  0x20000f34: all_tables
  0x20000f54: num_tables
  0x20000f58: packetbuf_aligned
  0x20001458: ip_processor_list_list
  0x2000145c: _link_stats_mem
  0x2000151c: current_callback
  0x20001520: packet_len.7097
  0x20001524: uipbuf_attrs
  0x20001530: uipbuf_default_attrs
  0x2000153c: tmp_ipaddr
  0x2000154c: default_prefix
  0x2000155c: loc_fipaddr
  0x2000156c: rand_time
  0x2000156e: uip_ext_len
  0x20001570: lastport
  0x20001572: node_id
  0x20001574: buframmem_memb_mem
  0x20003ed4: buflen
  0x20003ed6: bufptr
  0x20003ed8: num_sensors
  0x20003ed9: was_on
  0x20003eda: poll_mode
  0x20003edb: rf_flags
  0x20003edc: max_pm
  0x20003edd: racount
  0x20003ede: routememb_memb_used
  0x20003eee: neighborroutememb_memb_used
  0x20003efe: defaultroutermemb_memb_used
  0x20003f00: uip_ext_bitmap
  0x20003f01: uip_last_proto
  0x20003f02: nd6_opt_offset
  0x20003f03: packet.7062
  0x20004103: initialized
  0x20004104: fevent
  0x20004105: nevents
  0x20004106: poll_requested
  0x20004107: lastevent
  0x20004108: rxbuf_data
  0x20004188: overflow.5512
  0x20004189: buf.5518
  0x20004209: buframmem_memb_used
  0x20004211: bufmem_memb_used
  0x20004219: locked_map
  0x20004229: neighbor_addr_mem_memb_used
  0x20004239: used_map
  0x20004249: hdrlen
  0x2000424a: packet.7095
  0x2000444c: uip_ds6_timer_ra
  0x20004454: uip_ds6_if
  0x2000454c: uip_ds6_netif_addr_list_offset
  0x2000454d: uip_ds6_addr_size
  0x20004550: uip_ds6_prefix_list
  0x200045b0: uip_ds6_timer_periodic
  0x200045c0: uip_len
  0x200045c4: uip_sappdata
  0x200045c8: uip_lladdr
  0x200045d0: uip_aligned_buf
  0x20004ad0: uip_flags
  0x20004ad4: uip_udp_conn
  0x20004ad8: uip_appdata
  0x20004adc: uip_conn
  0x20004ae0: uip_slen
  0x20004ae4: uip_udp_conns
  0x20004be4: periodic_timer
  0x20004c04: nullnet_buf
  0x20004c08: nullnet_len
  0x20004c0a: packetbuf_addrs
  0x20004c1a: packetbuf_attrs
  0x20004c34: linkaddr_node_addr
  0x20004c3c: sensors_event
  0x20004c3d: sensors_flags
  0x20004c41: tcpip_event
  0x20004c42: button_hal_release_event
  0x20004c43: button_hal_periodic_event
  0x20004c44: button_hal_press_event
  0x20004c45: serial_line_event_message
  0x20004c46: _stack
  0x20004c48: stack
  0x20005448: _heap
  0x20008000: _eheap
