board:
  init_nsvtor: 0x8000000

interrupt:
  mode: round-robin
  trigger:
    on-infinite-sleep: true
    interval: 1000
  blocklist:
    - 35

memory_maps:
  - name: mmio
    address: 0x40000000
    size: 0x20000000
    type: mmio
  - name: ITM_DWT_BPU
    address: 0xe0000000
    size: 0x3000
    type: mmio
  - name: CTI
    address: 0xe0042000
    size: 0x1000
    type: mmio
  - name: zero
    address: 0x0
    size: 0x1000
    type: ram
  - name: ram
    address: 0x20000000
    size: 0x20000
    type: ram
  - name: text
    address: 0x8000000
    size: 0x14000
    file:
      path: uEmu.3Dprinter.bin
      length: 0x14000
    type: rom
  - name: rodata
    address: 0x8014000
    size: 0x3000
    permission:
      executable: false
    file:
      path: uEmu.3Dprinter.bin
      seek: 0x14000
    type: rom

symbols:
  - uEmu.3Dprinter.elf
